#!/usr/bin/env bash

# Assuming we're only running this script after completing the day's problems!
node index.js | tee ./answers.txt

fswatch -o . | xargs -n1 -I{} sh -c "\
  node index.js | \
  diff -q answers.txt - > /dev/null && \
    printf \"\033[32mPASS\033[m\n\" || \
    printf \"\033[31mFAIL\033[m\n\" \
"
