#!/usr/bin/env bash

if [ ! -f "./answers.txt" ]; then
  node index.js > ./answers.txt
fi

fswatch -o . | xargs -n1 -I{} sh -c "\
  node index.js | \
  diff -q answers.txt - > /dev/null && \
    printf \"\033[32mPASS\033[m\n\" || \
    printf \"\033[31mFAIL\033[m\n\" \
"
